platform :ios, '7.0'
target :QM_Nav_TabBar do

pod 'ReactiveCocoa', '~> 2.5'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'AFNetworking', '~> 2.6.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'MJExtension', '~> 3.0.7'
pod 'MJRefresh', '~> 2.4.11'
pod 'SDWebImage', '~> 3.7.3'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SDAutoLayout', '~> 1.3'
pod 'CustomIOSAlertView', '~> 0.9.5'

end